apiVersion: v1
kind: Service
metadata:
  name: dev-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    # nodePort: 32457
  selector:
    app: node-app
    enabled: "true"
