apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-cluster-dev.fullname" . }}-dev-loadbalancer
  labels:
    {{- include "eks-cluster-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loadBalancer.type }}
  ports:
    - port: {{ .Values.loadBalancer.port }}
      targetPort: http
      nodePort: {{ .Values.loadBalancer.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: node-app
    enabled: "true"
