apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-cluster-dev.fullname" . }}-dev-nodeport
  labels:
    {{- include "eks-cluster-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodePort.type }}
  ports:
    - port: {{ .Values.nodePort.port }}
      targetPort: {{ .Values.nodePort.targetPort }}
      protocol: TCP
  selector:
    app: node-app
    enabled: "true"
